apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 997807156382.dkr.ecr.ca-central-1.amazonaws.com/guestbook
  newTag: d6cbdc0df33ef5f5dce803931e4d89031865223b
- name: 997807156382.dkr.ecr.ca-central-1.amazonaws.com/guestbook
  newTag: c4b46b11a239ee926c00f11879a992a74f360e73
- name: frontend
  newName: guestbook
  newTag: 3fa38b9d2acb82a6e567c5935d1037a1339e4f1d
- name: guestbook
  newName: guestbook
  newTag: new
